### ISSUE TITLE
Improve StringBuilder toString() method

### ISSUE THREAD

**Issue by gurug-prog** [MatthewKirik/flex-log#2]
The StringBuilder class `toString()` method works using standart JS Array.prototype `join()` method.

```
toString() {
    return this.strings.join('');
}
```

That can be a reason of performance decrease. So if it's possible, we need to rewrite this method in a better way.

**Comment by MatthewKirik** [comment]
I'm not sure that is a major performance concern. I think using 'join' instead of concatenation is already good enough.
